server:
  port: 8080

spring:
  application:
    name: ms-registry
  swagger:
    enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka/

