server:
  port: 8081

spring:
  application:
    name: ms-dinners
#  swagger:
#    enabled: false

eureka:
  # UP (1) - 192.168.0.193:ms-gateway:80 新版默认就已经提供ip和端口啦
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

