server:
  port: 80

spring:
  application:
    name: ms-gateway
  swagger:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启配置注册中心进行路由功能
          lower-case-service-id: true # 将服务名称转换为小写
      routes:
        - id: ms-dinners
          uri: lb://ms-dinners
          predicates:
            - Path=/hello/**


eureka:
  # UP (1) - 192.168.0.193:ms-gateway:80 新版默认就已经提供ip和端口啦
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

