### 登录权限校验1
POST http://localhost:8082/oauth/token
Authorization: Basic appId 123456
Content-Type: application/x-www-form-urlencoded

username=test&password=123456&grant_type=password&scope=api

### 登录权限校验2 增强返回值
POST http://localhost:8082/oauth/token
Authorization: Basic appId 123456
Content-Type: application/x-www-form-urlencoded

username=test2&password=123456&grant_type=password&scope=api

### 获取用户信息 user/me
GET http://localhost:8082/user/me?access_token=b10793e7-57c4-4d34-af5c-38fd86585a76
